spectaql:
  logoFile: ./test/fixtures/logo.png
  faviconFile: ./test/fixtures/favicon.png
  displayAllServers: true
introspection:
  schemaFile: ./src/schema.gql
info:
  title: GraphQL API Reference
  description: Sample
  termsOfService: https://www.example.com/terms
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

servers:
  - url: https://example.com/graphql
    description: Production
    production: true