name: build

on:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - master
      - release/*
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  ui:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2.3.0
        with:
          node-version: "15"

      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build
        run: |
          cd ./ui
          npm install
          npm run build:prod

  api:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2.3.0
        with:
          node-version: "15"

      - name: Cache Node.js modules
        uses: actions/cache@v2.1.6
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      # install dependencies and build the project
      - name: Build
        run: |
          cd ./api
          npm install --registry=https://registry.npmjs.org
          npm run test:cov
          # Upload testing reports
          bash <(curl -s https://codecov.io/bash) -t api
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
 
