name: github pages

on:
  push:
    branches:
      - feature/ci-*  
    paths:
      - .github/workflows/**
      - docs/** 

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Create gh-pages-dir
        run: |
          mkdir -p ./public/

      - name: copy file
        run: |
          cp ./documents/index.html ./public/publish

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public